[target.aarch64-unknown-linux-gnu]
linker = "rust-lld"

[target.armv7-unknown-linux-gnueabihf]
linker = "rust-lld"

[target.aarch64-apple-ios]
linker = "rust-lld"

[target.x86_64-apple-ios]
linker = "rust-lld"
