[profile.release]
panic = "abort"
codegen-units = 1
lto = "thin"

[target.aarch64-linux-android]
linker = "aarch64-linux-android21-clang"
ar = "llvm-ar"

[target.wasm32-wasip1]
rustflags = ["-C", "opt-level=z"]
