#!/usr/bin/env python3
import subprocess
import sys

def main() -> int:
    if len(sys.argv) < 2:
        return 1
    rustc = sys.argv[1]
    args = []
    it = iter(sys.argv[2:])
    for arg in it:
        if arg == "--target":
            try:
                next_arg = next(it)
            except StopIteration:
                args.append(arg)
                break
            if next_arg == "wasm32-wasi":
                args.extend(["--target", "wasm32-wasip1"])
            else:
                args.extend(["--target", next_arg])
        elif arg.startswith("--target="):
            if arg == "--target=wasm32-wasi":
                args.append("--target=wasm32-wasip1")
            else:
                args.append(arg)
        else:
            args.append(arg)
    return subprocess.call([rustc, *args], close_fds=False)

if __name__ == "__main__":
    sys.exit(main())
