[package]
name = "zkprov-backend-native"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]

[dev-dependencies]
zkprov-corelib = { path = "../../corelib" }

[lib]
name = "zkprov_backend_native"
path = "src/lib.rs"
