[package]
name = "zkprov-backend-native"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
anyhow = { workspace = true }
zkprov-corelib = { path = "../../corelib" }

[dev-dependencies]
tempfile = "3.10.1"

[lib]
name = "zkprov_backend_native"
path = "src/lib.rs"
