name: CI

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install Foundry toolchain
        uses: foundry-rs/foundry-toolchain@v1
      - name: Build
        run: cargo build --workspace
      - name: Test
        run: cargo test --workspace --all-features -- --nocapture
      - name: Clippy
        run: cargo clippy --workspace --all-targets -- -D warnings
      - name: Format
        run: cargo fmt --all -- --check
